--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2026.1.39.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 01/06/2026 13:23:35
-- Server version: 9.7.0
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS agendadb_vivaaer;

CREATE DATABASE IF NOT EXISTS agendadb_vivaaer
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE agendadb_vivaaer;

--
-- Create table `contatos`
--
CREATE TABLE IF NOT EXISTS contatos (
  id_contato int NOT NULL AUTO_INCREMENT,
  nome varchar(100) NOT NULL,
  telefone varchar(20) NOT NULL,
  PRIMARY KEY (id_contato)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table contatos
--
INSERT INTO contatos(id_contato, nome, telefone) VALUES
(3, 'Vinicius', '1234567890()-+ '),
(4, 'Guilherme', '11968240809'),
(5, 'Claudemir', '1231234'),
(7, 'Mariusa', '1234567890'),
(8, 'Tomazia', '+55 11 24385178');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;